# Generated by Django 4.0.3 on 2022-05-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutField', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LearntModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learnField', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectField', models.TextField(default='<div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-1.jpg" />\n                        <center><em>Caption goes here</em></center>\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-2.jpg" />\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-3.jpg" />\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-4.jpg" />\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-5.jpg" />\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-6.jpg" />\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-7.jpg" />\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-8.jpg" />\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-9.jpg" />\n                    </div>')),
            ],
        ),
    ]
