# Generated by Django 4.0.3 on 2022-05-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPort', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JavaScriptModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('javascriptField', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='projectField',
            field=models.TextField(default='<div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-1.jpg" \n                        onclick="Swal.fire({\n                            title: \'Custom width, padding, color, background.\',\n                            width: 600,\n                            padding: \'3em\',\n                            color: \'#716add\',\n                            background: \'#fff url(/images/trees.png)\',\n                            backdrop: `\n                            rgba(0,0,123,0.4)\n                            url("/images/nyan-cat.gif")\n                            left top\n                            no-repeat\n                            `\n                            })\n                        "/>\n                        <center><em>Caption goes here</em></center>\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-2.jpg" onclick="\n                        Swal.fire(\'Any fool can use a computer\')" />\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-3.jpg" />\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-4.jpg" />\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-5.jpg" />\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-6.jpg" />\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-7.jpg" />\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-8.jpg" />\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-9.jpg" />\n                    </div>'),
        ),
    ]
