# Generated by Django 4.0.3 on 2022-05-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPort', '0002_javascriptmodel_alter_projectmodel_projectfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='javascriptmodel',
            name='javascriptField',
            field=models.TextField(default="\n                function myFirstFun() {\n                    Swal.fire('Hello world!')\n                }\n        "),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='projectField',
            field=models.TextField(default='<div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-1.jpg" \n                        onclick="Swal.fire({\n                            title: \'Custom width, padding, color, background.\',\n                            width: 600,\n                            padding: \'3em\',\n                            color: \'#716add\',\n                            background: \'#fff url(/images/trees.png)\',\n                            backdrop: `\n                            rgba(0,0,123,0.4)\n                            url("/images/nyan-cat.gif")\n                            left top\n                            no-repeat\n                            `\n                            })\n                        "/>\n                        <center><em>Caption goes here</em></center>\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-2.jpg" onclick="myFirstFun()" />\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-3.jpg" />\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-4.jpg" />\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-5.jpg" />\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-6.jpg" />\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-7.jpg" />\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-8.jpg" />\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-9.jpg" />\n                    </div>'),
        ),
    ]
