# Generated by Django 4.0.3 on 2022-05-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPort', '0004_alter_javascriptmodel_javascriptfield_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='javascriptmodel',
            name='javascriptField',
            field=models.TextField(default="function myFirstFun() {\n                    Swal.fire({\n                            title: 'Custom width, padding, color, background.',\n                            width: 600,\n                            padding: '3em',\n                            color: '#fff',\n                            background: '#1A1110',\n                            })\n                }\n        "),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='projectField',
            field=models.TextField(default='<div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-1.jpg" \n                        onclick="myFirstFun()" />\n                        <center><em>Caption goes here</em></center>\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-2.jpg" onclick="myFirstFun()" />\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-3.jpg" />\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-4.jpg" />\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-5.jpg" />\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-6.jpg" />\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-7.jpg" />\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-8.jpg" />\n                    </div>\n                    <div class="swiper-slide">\n                        <img src="https://swiperjs.com/demos/images/nature-9.jpg" />\n                    </div>'),
        ),
    ]
