# Generated by Django 4.0.3 on 2022-05-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPort', '0009_alter_projectmodel_projectfield_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('python', models.CharField(max_length=2)),
                ('django', models.CharField(max_length=2)),
                ('fsd', models.CharField(max_length=2)),
                ('dsa', models.CharField(max_length=2)),
                ('machine', models.CharField(max_length=2)),
                ('db', models.CharField(max_length=2)),
                ('problemSolving', models.CharField(max_length=2)),
                ('java', models.CharField(max_length=2)),
                ('graphicDesign', models.CharField(max_length=2)),
            ],
        ),
    ]
