# Generated by Django 4.0.3 on 2022-05-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPort', '0010_skillsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='projectField',
            field=models.TextField(default=' <div class="swiper mySwiper">\n        <div class="swiper-wrapper">\n          <div class="swiper-slide">\n            <a href="#modal">\n            <img src="https://drive.google.com/uc?export=view&id=11_KCAaYyeNgPUAL7kbPJ1ybuWNzxp43j" />\n            <center><em>School Management</em></center>\n          </div>\n          <div class="swiper-slide">\n            <img src="https://drive.google.com/uc?export=view&id=1cyW0esSTcYLR-SiUv--Pd5RzW-i0bStG" />\n          </div>\n          <div class="swiper-slide">\n            <img src="https://drive.google.com/uc?export=view&id=1m09zIqXaCEuN_zEwgYgXwVNJ2g5iskFh" /></a>\n          </div>\n          <div class="swiper-slide">\n            <img src="https://drive.google.com/uc?export=view&id=1QyxnsKv6smF2NmABYhdx3ci3ZGPX9g_p" />\n          </div>\n        </div>\n        <div class="swiper-pagination"></div>\n      </div>\n      </div>\n    </div>\n    </div>\n                    \n                    <! -- here modal box start add and change the name as required -->\n                     <!-- Modal -->\n                    <div class="modal-wrapper" id="modal">\n                    <div class="modal-body card">\n                        <div class="modal-header">\n                            <h2 class="heading">ProjectName</h2>\n                        </div>\n                        <h6>Why does it made?</h6>\n                        <p>this is made for</p>\n                        <h6>Things which made it possible.</h6>\n                        <p>java, html, css</p>\n                        <h6>What you learn?</h6>\n                        <p>I learn deeply</p>\n                    </div>\n                    <a href="#!" class="outside-trigger"></a>\n                </div>\n                    \n                    <! -- here modal box start add and change the name as required -->\n                     <!-- Modal -->\n                    <div class="modal-wrapper" id="modal">\n                    <div class="modal-body card">\n                        <div class="modal-header">\n                            <h2 class="heading">ProjectName</h2>\n                        </div>\n                        <h6>Why does it made?</h6>\n                        <p>this is made for</p>\n                        <h6>Things which made it possible.</h6>\n                        <p>java, html, css</p>\n                        <h6>What you learn?</h6>\n                        <p>I learn deeply</p>\n                    </div>\n                    <a href="#!" class="outside-trigger"></a>\n                </div>\n                    \n                    '),
        ),
    ]
