# Generated by Django 3.2.5 on 2022-05-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPort', '0013_alter_projectmodel_projectfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='projectField',
            field=models.TextField(default=' \n        <div class="swiper mySwiper">\n        <div class="swiper-wrapper">\n          <div class="swiper-slide">\n              <img src="https://drive.google.com/uc?export=view&id=1m09zIqXaCEuN_zEwgYgXwVNJ2g5iskFh" alt="" /></a>\n            <center><em>School Management</em></center>\n          <div class="swiper-slide">\n            <img src="https://drive.google.com/uc?export=view&id=1cyW0esSTcYLR-SiUv--Pd5RzW-i0bStG" alt="" />\n            <center><em>Arshskool</em></center>\n\n          </div>\n          <div class="swiper-slide">\n            <img src="https://drive.google.com/uc?export=view&id=1QyxnsKv6smF2NmABYhdx3ci3ZGPX9g_p" alt="" />\n            <center><em>Donation App</em></center>\n\n          </div>\n          <div class="swiper-slide">\n            <img src="https://drive.google.com/uc?export=view&id=11_KCAaYyeNgPUAL7kbPJ1ybuWNzxp43j" alt="" />\n            <center><em>Phishing Google SignIn</em></center>\n\n          </div>\n        </div>\n        <div class="swiper-pagination"></div>\n      </div>\n      </div>\n    </div>\n    </div>\n               \n                    '),
        ),
        migrations.AlterField(
            model_name='stylemodel',
            name='styleField',
            field=models.TextField(default='        \n\n\n        '),
        ),
    ]
