# Generated by Django 4.0.3 on 2022-05-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPort', '0015_seo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='projectField',
            field=models.TextField(default=' \n        <div class="swiper mySwiper">\n        <div class="swiper-wrapper">\n          <div class="swiper-slide">\n              <img src="https://drive.google.com/uc?export=view&id=1m09zIqXaCEuN_zEwgYgXwVNJ2g5iskFh" alt="" />\n            <center><em>School Management</em></center>\n            \n          <div class="swiper-slide">\n            <img src="https://drive.google.com/uc?export=view&id=1cyW0esSTcYLR-SiUv--Pd5RzW-i0bStG" alt="" />\n            <center><em>Arshskool</em></center>\n\n          </div>\n          <div class="swiper-slide">\n            <img src="https://drive.google.com/uc?export=view&id=1QyxnsKv6smF2NmABYhdx3ci3ZGPX9g_p" alt="" />\n            <center><em>Donation App</em></center>\n\n          </div>\n          <div class="swiper-slide">\n            <img src="https://drive.google.com/uc?export=view&id=11_KCAaYyeNgPUAL7kbPJ1ybuWNzxp43j" alt="" />\n            <center><em>Phishing Google SignIn</em></center>\n\n          </div>\n        </div>\n        <div class="swiper-pagination"></div>\n      </div>\n      </div>\n    </div>\n    </div>\n\n\n\n    <div class="swiper mySwiper">\n        <div class="swiper-wrapper">\n          <div class="swiper-slide">\n            <img src="https://drive.google.com/uc?export=view&id=1m09zIqXaCEuN_zEwgYgXwVNJ2g5iskFh" alt="SchoolManagement" />\n            <center><em>School Management</em></center>\n          </div>\n          <div class="swiper-slide">\n            1<img src="https://drive.google.com/uc?export=view&id=1cyW0esSTcYLR-SiUv--Pd5RzW-i0bStG" alt="Arshskool" />\n            <center><em>Arshskool</em></center>\n          </div>\n          <div class="swiper-slide">\n            <img src="https://drive.google.com/uc?export=view&id=1QyxnsKv6smF2NmABYhdx3ci3ZGPX9g_p" alt="DonationApp" />\n            <center><em>Donation App</em></center>\n          </div>\n          <div class="swiper-slide">\n            <img src="https://drive.google.com/uc?export=view&id=11_KCAaYyeNgPUAL7kbPJ1ybuWNzxp43j" alt="PhisingGoogle" />\n            <center><em>Phishing Google SignIn</em></center>\n          </div>         \n        </div>\n        <div class="swiper-pagination"></div>\n      </div>\n      </div>\n    </div>\n    </div>\n\n\n\n\n\n\n\n\n\n                    '),
        ),
        migrations.AlterField(
            model_name='seo',
            name='textArea',
            field=models.TextField(default='\n  <title>ArshErgon</title>\n    <meta charset="utf-8">\n    <meta name="TITLE" content="ArshErgon">\n    <meta name="creator" content="ArshErgon">\n    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">\n    <meta name="KEYWORDS" content="arshergon, programmer, web development">\n    <meta name="DESCRIPTION" content="ArshErgon is a web developer and designer based in Dehradun, Uttarakhand, India. He is a self-taught web developer and designer with a background in graphic design and digital media.">\n  '),
        ),
    ]
