# Generated by Django 4.0.3 on 2022-05-21 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPort', '0018_newhome_alter_projectmodel_projectfield'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newHome',
        ),
    ]
