# Generated by Django 4.0.3 on 2022-05-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPort', '0019_delete_newhome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutMeModel',
        ),
        migrations.AlterField(
            model_name='learntmodel',
            name='learnField',
            field=models.TextField(default='\n    Hey again! Through out the year I learn alot, \n    learn to work with different languages learn to workwith APIs, \n    I always try to push myself, to challenge myself more and more to know what’s my potential is, \n    what am I capable of doing better, I failed many times many of my projects got failed, I lost interest, \n    but I didn’t give up, maybe my \n    projects aren’t good as we compare to others, but I’m proud of it, \n    it helped me learn, and always challenge to go futher. Still have a long way, \n    I still didn’t know my potential yet!\n    '),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='projectField',
            field=models.TextField(default=' \n\n       <div class="swiper mySwiper">\n          <div class="swiper-wrapper">\n            <div class="swiper-slide">\n              <img src="https://drive.google.com/uc?export=view&id=1m09zIqXaCEuN_zEwgYgXwVNJ2g5iskFh" alt="SchoolManagement" />\n              <center><em>School Management</em></center>\n            </div>\n            <div class="swiper-slide">\n              <img src="https://drive.google.com/uc?export=view&id=1cyW0esSTcYLR-SiUv--Pd5RzW-i0bStG" alt="Arshskool" />\n              <center><em>Arshskool</em></center>\n            </div>\n            <div class="swiper-slide">\n              <img src="https://drive.google.com/uc?export=view&id=1QyxnsKv6smF2NmABYhdx3ci3ZGPX9g_p" alt="DonationApp" />\n              <center><em>Donation App</em></center>\n            </div>\n            <div class="swiper-slide">\n              <img src="https://drive.google.com/uc?export=view&id=11_KCAaYyeNgPUAL7kbPJ1ybuWNzxp43j" alt="PhisingGoogle" />\n              <center><em>Phishing Google SignIn</em></center>\n            </div>         \n          </div>\n        </div>\n        </div>\n      </div>\n      </div>\n    \n  '),
        ),
    ]
