# Generated by Django 4.0.3 on 2022-05-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPort', '0020_delete_aboutmemodel_alter_learntmodel_learnfield_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='projectField',
            field=models.TextField(default=' \n\n\n\n       <div class="swiper mySwiper">\n          <div class="swiper-wrapper">\n            <div class="swiper-slide">\n              <img src="https://drive.google.com/uc?export=view&id=11_KCAaYyeNgPUAL7kbPJ1ybuWNzxp43j" alt="SchoolManagement" />\n              <center><em>School Management</em></center>\n            </div>\n            <div class="swiper-slide">\n              <img src="https://drive.google.com/uc?export=view&id=1m09zIqXaCEuN_zEwgYgXwVNJ2g5iskFh" alt="Arshskool" />\n              <center><em>Arshskool</em></center>\n            </div>\n            <div class="swiper-slide">\n              <img src="https://drive.google.com/uc?export=view&id=1cyW0esSTcYLR-SiUv--Pd5RzW-i0bStG" alt="DonationApp" />\n              <center><em>Donation App</em></center>\n            </div>\n            <div class="swiper-slide">\n              <img src="https://drive.google.com/uc?export=view&id=1QyxnsKv6smF2NmABYhdx3ci3ZGPX9g_p" alt="PhisingGoogle" />\n              <center><em>Phishing Google SignIn</em></center>\n            </div>         \n          </div>\n        </div>\n        </div>\n      </div>\n      </div>\n    \n  '),
        ),
    ]
